// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWjQ-TEX4mjrxgCQ5zWlt8xrF97m5sKHI',
    appId: '1:562815097185:web:f2b12e789fe92b94f08d20',
    messagingSenderId: '562815097185',
    projectId: 'app-nutricao-60dbd',
    authDomain: 'app-nutricao-60dbd.firebaseapp.com',
    storageBucket: 'app-nutricao-60dbd.appspot.com',
    measurementId: 'G-T2WK8W7773',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHoibP3YYtT6sn-ysM8wyWpkIyCs65KxI',
    appId: '1:562815097185:android:a7a1176bc8d76e66f08d20',
    messagingSenderId: '562815097185',
    projectId: 'app-nutricao-60dbd',
    storageBucket: 'app-nutricao-60dbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB80pNxFY5BnV4G4mB4DAIvu9ntEa8L5XU',
    appId: '1:562815097185:ios:9fe036433549158ef08d20',
    messagingSenderId: '562815097185',
    projectId: 'app-nutricao-60dbd',
    storageBucket: 'app-nutricao-60dbd.appspot.com',
    iosClientId: '562815097185-3hp6nq4ug49q7ps46gi9eq04tcg7jge1.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutricaoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB80pNxFY5BnV4G4mB4DAIvu9ntEa8L5XU',
    appId: '1:562815097185:ios:3beb6a3f8019a68ff08d20',
    messagingSenderId: '562815097185',
    projectId: 'app-nutricao-60dbd',
    storageBucket: 'app-nutricao-60dbd.appspot.com',
    iosClientId: '562815097185-d4ljl9boudvhments8evrti5sf0ul9e5.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutricaoApp.RunnerTests',
  );
}
